spring.application.name=demo

# Conexión MySQL con variables de entorno
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/zona_fit_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Desactivar tomcat (si es solo backend sin web)
spring.main.web-application-type=servlet

# Configuración adicional de conexión
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5