apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-prod-pv-1
  labels:
    type: local
    app: postgres
    instance: "1"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/k8s-storage/instance-1/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vps-dc33a175.vps.ovh.ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-prod-pv-1
  labels:
    type: local
    app: redis
    instance: "1"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/k8s-storage/instance-1/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vps-dc33a175.vps.ovh.ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv-1
  labels:
    type: local
    app: traefik
    instance: "1"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/k8s-storage/instance-1/traefik
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vps-dc33a175.vps.ovh.ca