apiVersion: v1
kind: ConfigMap
metadata:
  name: swag-proxy-configs-1
  labels:
    app: swag
    generated-by: script
    instance: "1"
data:
  http-challenge.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name iyata.duckdns.org *.iyata.duckdns.org;
        
        # Challenge de Let's Encrypt
        location /.well-known/acme-challenge/ {
            root /config/www;
            try_files $uri =404;
        }
        
        # Todo lo demás redirige a HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }
    
  # Proxy para tu API Go
  go-api.subdomain.conf: |
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name api.iyata.duckdns.org;
        
        include /config/nginx/ssl.conf;
        
        client_max_body_size 0;

        # RESOLVER CRÍTICO: Usar el servicio CoreDNS de Kubernetes
        resolver 10.96.0.10 valid=10s;  # IP del servicio kube-dns
        resolver_timeout 5s;

        location / {
            set $backend "go-api-service-1:4000";
            proxy_pass http://$backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Configuraciones adicionales para timeouts
            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;
        }

        location /health {
            set $backend_health "go-api-service-1:4000";
            proxy_pass http://$backend_health/health;
            proxy_set_header Host $host;
        }
    }

  www.subdomain.conf: |
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name www.iyata.duckdns.org;
        
        include /config/nginx/ssl.conf;

        return 301 https://iyata.duckdns.org$request_uri;
    }
  
  
  default.conf: |
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name iyata.duckdns.org;
        
        include /config/nginx/ssl.conf;
        
        # Redirige el dominio principal a www
        return 301 https://www.iyata.duckdns.org$request_uri;
    }
    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        server_name _;
        
        include /config/nginx/ssl.conf;
        
        # Redirige cualquier subdominio no configurado a www
        return 301 https://www.iyata.duckdns.org$request_uri;
    }
    
    include /config/nginx/proxy-confs/*.subdomain.conf;
