services:
  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    networks:
      - my_lan_internal
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=iyata.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=1cfb6881-33ac-4c48-a8b2-2a46f73779e8
      - EMAIL=martinciro11@gmail.com
      - HTTP_PROXY=http://squid-proxy:3128
      - HTTPS_PROXY=http://squid-proxy:3128
      - NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.svc.cluster.local
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    networks:
      - my_lan_internal
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBDOMAINS=iyata
      - TOKEN=token
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    restart: always

  
networks:
  my_lan_internal:
    external: true