apiVersion: v1
data:
  traefik.yaml: |
    api:
      dashboard: true
      insecure: true
    certificatesResolvers:
      letsencrypt:
        acme:
          email: martinciro11@gmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"traefik.yaml":"api:\n  dashboard: true\n  insecure: true\ncertificatesResolvers:\n  letsencrypt:\n    acme:\n      email: martinciro11@gmail.com\n      storage: /data/acme.json\n      httpChallenge:\n        entryPoint: web\nentryPoints:\n  web:\n    address: \":80\"\n    http:\n      redirections:\n        entryPoint:\n          to: websecure\n          scheme: https\n  websecure:\n    address: \":443\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"traefik-config","namespace":"traefik"}}
  creationTimestamp: "2025-11-29T03:17:08Z"
  name: traefik-config
  namespace: traefik
  resourceVersion: "262467"
  uid: 4f13ecf1-42be-42c4-a6ff-ceee1fec4364
