apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    generated-by: script
    created: 2025-11-01
    source: env-file
type: Opaque
data:
  postgres-password: ICAg4pyFIFVzaW5nIFBBU1NfREI6IERhdGFiYXNlIFBhc3N3b3JkCmNpcm8=
