apiVersion: v1
kind: Service
metadata:
  name: postgres-service-1
  labels:
    app: postgres
    tier: database
    instance: "1"
spec:
  selector:
    app: postgres
    tier: database
    instance: "1"
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP