apiVersion: v1
kind: Service
metadata:
  name: redis-service-1
  labels:
    app: redis
    tier: cache
    instance: "1"
spec:
  selector:
    app: redis
    tier: cache
    instance: "1"
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP